package interfaz;

import java.sql.SQLException;

public interface Conection {
    void conectar() throws SQLException;
}

//EN UN PROGRAMA REAL
//EL USUARIO ACCEDE A LAS INTERFACES, NO A LAS CLASES, NI TAMPOCO AL COMPORTAMIENTO DE LA MISMA
//A ESTO SE LE LLAMA API, SON TODAS LAS REGLAS QUE UN USUARIO DEBE SEGUIR PARA PODER UTILIZAR
//LAS DISTINTAS FUNCIONALIDADES DE UN PROGRAMA.

//PARA NOSOTROS, LOS PROGRAMADORES, UNA API ES UN DOCUMENTO JAVADOCS CON LA INFORMACIÓN NECESARIA
//LAS INTERFACES, LAS CLASES Y LOS MÉTODOS A UTILIZAR

//PARA UN USUARIO PROMEDIO ESTO SE REDUCE A SIMPLES GUI.
//PERO, PARA LAS CLASES INTERNAS --Y ACÁ ESTÁ LA MAGIA DE LA INTERFAZ--
//LAS CLASES SE COMUNICAN MEDIANTE INTERFACES, DE FORMA QUE NINGUNA
//TIENE UNA RELACIÓN FUERTE CON LA OTRA Y NINGUNA SABE CÓMO OPERA LA OTRA.
//ÚNICAMENTE SABEN QUE LAS COSAS FUNCIONAN CUANDO ACCEDEN A DETERMINADO PUNTO.

//POR ENDE, EL TRUCO ES INTERFAZ -> CLASE ABSTRACTA -> CLASE DE IMPLEMENTACIÓN -> USUARIO DESTINO.
//EL USUARIO TIENE UNA DEPENDENCIA A LA CLASE ABSTRACTA, PERO REALMENTE ES UNA DEPENDENCIA A LA INTERFAZ
//IMPLEMENTADA.

//NO IMPORTA SI CAMBIAMOS EL COMPORTAMIENTO INTERNO, O SI LE INDICAMOS OTRA CLASE.
//PARA LA CLASE CLIENTE, NADA CAMBIARÁ.

//LAS INTERFACES DEFINEN CÓMO DEBE SER UN COMPORTAMIENTO.
//PERO NO LA IMPLEMENTACIÓN.
//DE TAL FORMA QUE CUALQUIERA PUEDE IMPLEMENTARLO Y OFRECERLE UN SERVICIO A LA CLASE CLIENTE.

//EL CLIENTE SABE QUE RECIBE UN SERVICIO, PERO NO SABE DE QUIÉN NI CÓMO.

//USTEDES SE METEN A INTERNET, BUSCAN COSAS EN INTERNET. ¿PERO SABEN CÓMO FUNCIONA INTERNET?
//¿LES IMPORTA SABERLO? ¿SI INTERNET CAMBIA SU COMPORTAMIENTO INTERNO, PERO LO QUE RECIBEN
//SIGUE SIENDO LO MISMO, LO NOTARÁN?

//¡¡EXACTO!!

//PARA QUE INDEPENDIENTE DE LA IMPLEMENTACIÓN, EL CLIENTE RECIBA EL MISMO SERVICIO.

//INTERFAZ + CLASE ABSTRACTA + CLASE CONCRETA + APP

//CLIENTE -> ACCEDE A INTERFAZ -> IMPLEMENTADA POR CLASE ABSTRACTA -> QUE ES RELLENADA E
//IMPLEMENTADA POR CLASE CONCRETA.

//CLASE ABSTRACTA: FORMULARIO.
//LA INTERFAZ ES EQUIVALENTE: API O REGLAS DE COMPORTAMIENTO POR LAS QUE SE MOVERÁ EL CLIENTE.

//CLASE CONCRETA: LE DA USO A LA INTERFAZ, DECIDE CÓMO SE LLEVARÁ A CABO TODO LO QUE LA INTERFAZ
//ESPECIFICA Y RELLENA LOS CAMPOS DEL FORMULARIO.

//CLIENTE: EL CLIENTE ACCEDE ÚNICAMENTE AL PROGRAMA MEDIANTE LAS REGLAS, ES DECIR LA INTERFAZ.
//Y SU CONOCIMIENTO SE LIMITA ÚNICAMENTE A LAS ESPECIFICACIONES, MÁS NO A LAS IMPLEMENTACIONES.

//EN EL TARGET... LA INTERFAZ QUEDA RELLENA CON EL COMPORTAMIENTO DE LA CLASE CONCRETA.

//AAAAH, BIEN AHÍ.
//POR CADA CLIENTE, QUEDA RELLENADA POR CADA COMPORTAMIENTO.
//ESO SE HACE CON HILOS Y ES LO QUE HACE UN SERVIDOR.

//CADA HILO, IMPLEMENTA DE FORMA DISTINTA LA INTERFAZ.